FROM nginx
ADD dist /usr/share/nginx/html
LABEL org.opencontainers.image.source="https://github.com/gaspard/rescript-react-vite-tailwind"
LABEL org.opencontainers.image.description="A trivial app served by Nginx."